Created String1
mpieron/CodingBat pull request #2
Opened 2021-11-25 14:25 UTC by mpieron

Added String1 tasks

2021-11-26 12:40 UTC, ghostdance386 commented on src/String1/SeeColor.java
> +        return "";
You could use startsWith() method from String class to check that

2021-11-29 07:53 UTC, ghostdance386 requested changes
I did not check all of the classes, but my comments probably could be applied to these unchecked as well. Please make the changes in all classes where they apply and request review again

2021-11-29 07:53 UTC, ghostdance386 commented on src/String1/ExtraFront.java
> +        return chars + chars + chars;
You could use repeat() from String class

2021-11-29 07:53 UTC, ghostdance386 commented on src/String1/ExtraFront.java
> +            chars = str.substring(0,2);
for simple if-else scenarios, You can use ternary operator. In this case it would like this: chars = str.length() < 2 ? str : str.substring(0,2);
If You're not familiar with this syntax, please find some materials about it

2021-11-29 07:53 UTC, ghostdance386 commented on src/String1/HelloName.java
> +        return "Hello " + name + "!";
You can use format() method from String class to create strings that will contain some variable in them. Here it would look like this: String.format("Hello %s!", name);

2021-11-29 07:53 UTC, ghostdance386 commented on src/String1/EndsLy.java
> +            return str.substring(str.length()-2).equals("ly");
You could use endsWith() from String class

2021-11-30 08:59 UTC, kdyla-griddynamics approved these changes

2021-11-30 09:10 UTC, merged